/**
 * GENERATED by `npm run clues` — do not edit.
 *
 * Every clue in here is measured by exhaustive search over the real substrate,
 * so a tier-one hint is a fact rather than an author's opinion. The search is
 * far too slow to run on a phone, which is why it is a table.
 */

export interface LevelClues {
  optimum: { parts: number; depth: number } | null;
  par: { components: number; ticks: number };
  structure: string[];
  netlist: string[];
  exhaustive: boolean;
}

export const CLUES: Record<string, LevelClues> = {
  "continuity": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "No node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = a"
    ],
    "exhaustive": true
  },
  "invert": {
    "optimum": {
      "parts": 1,
      "depth": 1
    },
    "par": {
      "components": 1,
      "ticks": 1
    },
    "structure": [
      "No node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = a",
      "n1 = NOT(n0)"
    ],
    "exhaustive": true
  },
  "fanout": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "No node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = a"
    ],
    "exhaustive": true
  },
  "either": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "One node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = a | b"
    ],
    "exhaustive": true
  },
  "crossing": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "No node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a"
    ],
    "exhaustive": true
  },
  "neither": {
    "optimum": {
      "parts": 1,
      "depth": 1
    },
    "par": {
      "components": 1,
      "ticks": 1
    },
    "structure": [
      "One node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = a | b",
      "n1 = NOT(n0)"
    ],
    "exhaustive": true
  },
  "not-both": {
    "optimum": {
      "parts": 2,
      "depth": 1
    },
    "par": {
      "components": 2,
      "ticks": 1
    },
    "structure": [
      "One node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = NOT(n0) | NOT(n1)"
    ],
    "exhaustive": true
  },
  "both": {
    "optimum": {
      "parts": 3,
      "depth": 2
    },
    "par": {
      "components": 3,
      "ticks": 2
    },
    "structure": [
      "One node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = NOT(n0) | NOT(n1)",
      "n3 = NOT(n2)"
    ],
    "exhaustive": true
  },
  "copy": {
    "optimum": {
      "parts": 4,
      "depth": 2
    },
    "par": {
      "components": 4,
      "ticks": 2
    },
    "structure": [
      "No node is driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = c",
      "n1 = b",
      "n2 = OR(n0,n1)",
      "n3 = NOT(n2)",
      "n4 = a",
      "n5 = OR(n1,n4)",
      "n6 = NOT(n5)"
    ],
    "exhaustive": true
  },
  "one-or-other": {
    "optimum": {
      "parts": 6,
      "depth": 2
    },
    "par": {
      "components": 6,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = NOT(n0) | BUF(n1)",
      "n3 = NOT(n1) | BUF(n0)",
      "n4 = NOT(n2) | NOT(n3)"
    ],
    "exhaustive": true
  },
  "half-adder": {
    "optimum": {
      "parts": 7,
      "depth": 3
    },
    "par": {
      "components": 9,
      "ticks": 2
    },
    "structure": [
      "2 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = OR(n0,n1)",
      "n3 = NOT(n0) | NOT(n1)",
      "n4 = NOT(n3)",
      "n5 = NOT(n2) | NOT(n3)",
      "n6 = NOT(n5)"
    ],
    "exhaustive": true
  },
  "full-adder": {
    "optimum": null,
    "par": {
      "components": 18,
      "ticks": 4
    },
    "structure": [
      "9 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = a",
      "n1 = NOT(n6) | NOT(n7)",
      "n2 = NOT(n9) | NOT(n10)",
      "n3 = b",
      "n4 = NOT(n8) | NOT(n11)",
      "n5 = cin",
      "n6 = NOT(n0) | BUF(n3)",
      "n7 = NOT(n3) | BUF(n0)",
      "n8 = NOT(n0) | NOT(n3)",
      "n9 = NOT(n1) | BUF(n5)",
      "n10 = NOT(n5) | BUF(n1)",
      "n11 = NOT(n1) | NOT(n5)"
    ],
    "exhaustive": true
  },
  "hold": {
    "optimum": {
      "parts": 1,
      "depth": 0
    },
    "par": {
      "components": 1,
      "ticks": 0
    },
    "structure": [
      "One node is driven by more than one thing.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: BUF."
    ],
    "netlist": [
      "n0 = a | BUF(n0)"
    ],
    "exhaustive": true
  },
  "set-reset": {
    "optimum": {
      "parts": 2,
      "depth": 1
    },
    "par": {
      "components": 2,
      "ticks": 1
    },
    "structure": [
      "2 of its nodes are driven by more than one thing.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = s | NOT(n1)",
      "n1 = r | NOT(n0)"
    ],
    "exhaustive": true
  },
  "enable": {
    "optimum": {
      "parts": 5,
      "depth": 2
    },
    "par": {
      "components": 5,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = s | NOT(n2)",
      "n1 = en | NOT(n2)",
      "n2 = r | NOT(n0) | NOT(n1)",
      "n3 = NOT(n2)"
    ],
    "exhaustive": true
  },
  "gated": {
    "optimum": null,
    "par": {
      "components": 6,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components.",
      "It places one of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d",
      "n1 = NOT(n0) | NOT(n3)",
      "n2 = NOT(n1) | NOT(n4)",
      "n3 = en",
      "n4 = BUF(n3) | NOT(n2)"
    ],
    "exhaustive": false
  },
  "edge": {
    "optimum": null,
    "par": {
      "components": 13,
      "ticks": 5
    },
    "structure": [
      "6 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d",
      "n1 = NOT(n5) | NOT(n6)",
      "n2 = clk",
      "n3 = NOT(n2)",
      "n4 = NOT(n7) | NOT(n8)",
      "n5 = NOT(n0) | NOT(n3)",
      "n6 = NOT(n1) | BUF(n3)",
      "n7 = NOT(n1) | NOT(n2)",
      "n8 = NOT(n4) | BUF(n2)"
    ],
    "exhaustive": false
  },
  "divide": {
    "optimum": {
      "parts": 8,
      "depth": 5
    },
    "par": {
      "components": 14,
      "ticks": 3
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = clk",
      "n1 = NOT(n0) | NOT(n2)",
      "n2 = NOT(n0)",
      "n3 = NOT(n1) | NOT(n4)",
      "n4 = NOT(n1) | NOT(n3)",
      "n5 = NOT(n4)"
    ],
    "exhaustive": true
  },
  "two-of-them": {
    "optimum": null,
    "par": {
      "components": 26,
      "ticks": 5
    },
    "structure": [
      "12 of its nodes are driven by more than one thing.",
      "One signal is read by 6 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d0",
      "n1 = NOT(n9) | NOT(n10)",
      "n2 = clk",
      "n3 = d1",
      "n4 = NOT(n15) | NOT(n16)",
      "n5 = NOT(n2)",
      "n6 = NOT(n7) | NOT(n8)",
      "n7 = NOT(n0) | NOT(n5)",
      "n8 = NOT(n6) | BUF(n5)",
      "n9 = NOT(n6) | NOT(n2)",
      "n10 = NOT(n1) | BUF(n2)",
      "n11 = NOT(n2)",
      "n12 = NOT(n13) | NOT(n14)",
      "n13 = NOT(n3) | NOT(n11)",
      "n14 = NOT(n12) | BUF(n11)",
      "n15 = NOT(n12) | NOT(n2)",
      "n16 = NOT(n4) | BUF(n2)"
    ],
    "exhaustive": false
  },
  "only-when-told": {
    "optimum": null,
    "par": {
      "components": 19,
      "ticks": 4
    },
    "structure": [
      "9 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It places one of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d",
      "n1 = NOT(n0) | NOT(n3)",
      "n2 = NOT(n1) | NOT(n6)",
      "n3 = we",
      "n4 = NOT(n11) | NOT(n12)",
      "n5 = clk",
      "n6 = BUF(n3) | NOT(n4)",
      "n7 = NOT(n5)",
      "n8 = NOT(n9) | NOT(n10)",
      "n9 = NOT(n2) | NOT(n7)",
      "n10 = NOT(n8) | BUF(n7)",
      "n11 = NOT(n8) | NOT(n5)",
      "n12 = NOT(n4) | BUF(n5)"
    ],
    "exhaustive": false
  },
  "count-to-three": {
    "optimum": null,
    "par": {
      "components": 28,
      "ticks": 6
    },
    "structure": [
      "12 of its nodes are driven by more than one thing.",
      "One signal is read by 4 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = NOT(n1)",
      "n1 = NOT(n9) | NOT(n10)",
      "n2 = clk",
      "n3 = NOT(n4)",
      "n4 = NOT(n15) | NOT(n16)",
      "n5 = NOT(n2)",
      "n6 = NOT(n7) | NOT(n8)",
      "n7 = NOT(n0) | NOT(n5)",
      "n8 = NOT(n6) | BUF(n5)",
      "n9 = NOT(n6) | NOT(n2)",
      "n10 = NOT(n1) | BUF(n2)",
      "n11 = NOT(n0)",
      "n12 = NOT(n13) | NOT(n14)",
      "n13 = NOT(n3) | NOT(n11)",
      "n14 = NOT(n12) | BUF(n11)",
      "n15 = NOT(n12) | NOT(n0)",
      "n16 = NOT(n4) | BUF(n0)"
    ],
    "exhaustive": true
  },
  "one-of-four": {
    "optimum": null,
    "par": {
      "components": 12,
      "ticks": 2
    },
    "structure": [
      "4 of its nodes are driven by more than one thing.",
      "One signal is read by 4 different components.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = a",
      "n1 = BUF(n0) | BUF(n3)",
      "n2 = NOT(n1)",
      "n3 = b",
      "n4 = NOT(n0) | BUF(n3)",
      "n5 = NOT(n4)",
      "n6 = BUF(n0) | NOT(n3)",
      "n7 = NOT(n6)",
      "n8 = NOT(n0) | NOT(n3)",
      "n9 = NOT(n8)"
    ],
    "exhaustive": true
  },
  "naught-and-one": {
    "optimum": {
      "parts": 3,
      "depth": 3
    },
    "par": {
      "components": 3,
      "ticks": 1
    },
    "structure": [
      "No node is driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = x",
      "n1 = NOT(n0)",
      "n2 = OR(n0,n1)",
      "n3 = NOT(n2)"
    ],
    "exhaustive": true
  },
  "every-digit": {
    "optimum": null,
    "par": {
      "components": 8,
      "ticks": 1
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = n0",
      "n1 = n1",
      "n2 = n2",
      "n3 = n3",
      "n4 = NOT(n1)",
      "n5 = NOT(n1) | BUF(n1)",
      "n6 = NOT(n2)",
      "n7 = BUF(n0) | BUF(n2)",
      "n8 = BUF(n2) | BUF(n3)"
    ],
    "exhaustive": false
  },
  "show-the-count": {
    "optimum": null,
    "par": {
      "components": 49,
      "ticks": 8
    },
    "structure": [
      "19 of its nodes are driven by more than one thing.",
      "One signal is read by 6 different components.",
      "It places 3 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = clk",
      "n1 = NOT(n19) | NOT(n20)",
      "n2 = NOT(n27)",
      "n3 = NOT(n4)",
      "n4 = NOT(n28)",
      "n5 = NOT(n4) | BUF(n4)",
      "n6 = NOT(n25) | NOT(n26)",
      "n7 = NOT(n29)",
      "n8 = NOT(n7)",
      "n9 = NOT(n30)",
      "n10 = BUF(n2) | BUF(n7)",
      "n11 = BUF(n2)",
      "n12 = BUF(n7) | BUF(n9)",
      "n13 = NOT(n1)",
      "n14 = NOT(n6)",
      "n15 = NOT(n0)",
      "n16 = NOT(n17) | NOT(n18)",
      "n17 = NOT(n13) | NOT(n15)",
      "n18 = NOT(n16) | BUF(n15)",
      "n19 = NOT(n16) | NOT(n0)",
      "n20 = NOT(n1) | BUF(n0)",
      "n21 = NOT(n13)",
      "n22 = NOT(n23) | NOT(n24)",
      "n23 = NOT(n14) | NOT(n21)",
      "n24 = NOT(n22) | BUF(n21)",
      "n25 = NOT(n22) | NOT(n13)",
      "n26 = NOT(n6) | BUF(n13)",
      "n27 = BUF(n1) | BUF(n6)",
      "n28 = NOT(n1) | BUF(n6)",
      "n29 = BUF(n1) | NOT(n6)",
      "n30 = NOT(n1) | NOT(n6)"
    ],
    "exhaustive": false
  }
};
