/**
 * GENERATED by `npm run clues` — do not edit.
 *
 * Every clue in here is measured by exhaustive search over the real substrate,
 * so a tier-one hint is a fact rather than an author's opinion. The search is
 * far too slow to run on a phone, which is why it is a table.
 */

export interface LevelClues {
  optimum: { parts: number; depth: number } | null;
  par: { components: number; ticks: number };
  structure: string[];
  netlist: string[];
  exhaustive: boolean;
}

export const CLUES: Record<string, LevelClues> = {
  "continuity": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "No node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = a"
    ],
    "exhaustive": true
  },
  "invert": {
    "optimum": {
      "parts": 1,
      "depth": 1
    },
    "par": {
      "components": 1,
      "ticks": 1
    },
    "structure": [
      "No node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = a",
      "n1 = NOT(n0)"
    ],
    "exhaustive": true
  },
  "fanout": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "No node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = a"
    ],
    "exhaustive": true
  },
  "either": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "One node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = a | b"
    ],
    "exhaustive": true
  },
  "crossing": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "No node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a"
    ],
    "exhaustive": true
  },
  "neither": {
    "optimum": {
      "parts": 1,
      "depth": 1
    },
    "par": {
      "components": 1,
      "ticks": 1
    },
    "structure": [
      "One node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = a | b",
      "n1 = NOT(n0)"
    ],
    "exhaustive": true
  },
  "not-both": {
    "optimum": {
      "parts": 2,
      "depth": 1
    },
    "par": {
      "components": 2,
      "ticks": 1
    },
    "structure": [
      "One node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = NOT(n0) | NOT(n1)"
    ],
    "exhaustive": true
  },
  "both": {
    "optimum": {
      "parts": 3,
      "depth": 2
    },
    "par": {
      "components": 3,
      "ticks": 2
    },
    "structure": [
      "One node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = NOT(n0) | NOT(n1)",
      "n3 = NOT(n2)"
    ],
    "exhaustive": true
  },
  "copy": {
    "optimum": {
      "parts": 4,
      "depth": 2
    },
    "par": {
      "components": 4,
      "ticks": 2
    },
    "structure": [
      "No node is driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = c",
      "n1 = b",
      "n2 = OR(n0,n1)",
      "n3 = NOT(n2)",
      "n4 = a",
      "n5 = OR(n1,n4)",
      "n6 = NOT(n5)"
    ],
    "exhaustive": true
  },
  "one-or-other": {
    "optimum": {
      "parts": 6,
      "depth": 2
    },
    "par": {
      "components": 6,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = NOT(n0) | BUF(n1)",
      "n3 = NOT(n1) | BUF(n0)",
      "n4 = NOT(n2) | NOT(n3)"
    ],
    "exhaustive": true
  },
  "half-adder": {
    "optimum": {
      "parts": 7,
      "depth": 3
    },
    "par": {
      "components": 9,
      "ticks": 2
    },
    "structure": [
      "2 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = OR(n0,n1)",
      "n3 = NOT(n0) | NOT(n1)",
      "n4 = NOT(n3)",
      "n5 = NOT(n2) | NOT(n3)",
      "n6 = NOT(n5)"
    ],
    "exhaustive": true
  },
  "full-adder": {
    "optimum": null,
    "par": {
      "components": 18,
      "ticks": 4
    },
    "structure": [
      "9 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = a",
      "n1 = NOT(n6) | NOT(n7)",
      "n2 = NOT(n9) | NOT(n10)",
      "n3 = b",
      "n4 = NOT(n8) | NOT(n11)",
      "n5 = cin",
      "n6 = NOT(n0) | BUF(n3)",
      "n7 = NOT(n3) | BUF(n0)",
      "n8 = NOT(n0) | NOT(n3)",
      "n9 = NOT(n1) | BUF(n5)",
      "n10 = NOT(n5) | BUF(n1)",
      "n11 = NOT(n1) | NOT(n5)"
    ],
    "exhaustive": true
  },
  "hold": {
    "optimum": {
      "parts": 1,
      "depth": 0
    },
    "par": {
      "components": 1,
      "ticks": 0
    },
    "structure": [
      "One node is driven by more than one thing.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: BUF."
    ],
    "netlist": [
      "n0 = a | BUF(n0)"
    ],
    "exhaustive": true
  },
  "set-reset": {
    "optimum": {
      "parts": 2,
      "depth": 1
    },
    "par": {
      "components": 2,
      "ticks": 1
    },
    "structure": [
      "2 of its nodes are driven by more than one thing.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = s | NOT(n1)",
      "n1 = r | NOT(n0)"
    ],
    "exhaustive": true
  },
  "enable": {
    "optimum": {
      "parts": 5,
      "depth": 2
    },
    "par": {
      "components": 5,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = s | NOT(n2)",
      "n1 = en | NOT(n2)",
      "n2 = r | NOT(n0) | NOT(n1)",
      "n3 = NOT(n2)"
    ],
    "exhaustive": true
  },
  "gated": {
    "optimum": null,
    "par": {
      "components": 6,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components.",
      "It places one of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d",
      "n1 = NOT(n0) | NOT(n3)",
      "n2 = NOT(n1) | NOT(n4)",
      "n3 = en",
      "n4 = BUF(n3) | NOT(n2)"
    ],
    "exhaustive": false
  },
  "edge": {
    "optimum": null,
    "par": {
      "components": 13,
      "ticks": 5
    },
    "structure": [
      "6 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d",
      "n1 = NOT(n5) | NOT(n6)",
      "n2 = clk",
      "n3 = NOT(n2)",
      "n4 = NOT(n7) | NOT(n8)",
      "n5 = NOT(n0) | NOT(n3)",
      "n6 = NOT(n1) | BUF(n3)",
      "n7 = NOT(n1) | NOT(n2)",
      "n8 = NOT(n4) | BUF(n2)"
    ],
    "exhaustive": false
  },
  "divide": {
    "optimum": {
      "parts": 8,
      "depth": 5
    },
    "par": {
      "components": 14,
      "ticks": 3
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = clk",
      "n1 = NOT(n0) | NOT(n2)",
      "n2 = NOT(n0)",
      "n3 = NOT(n1) | NOT(n4)",
      "n4 = NOT(n1) | NOT(n3)",
      "n5 = NOT(n4)"
    ],
    "exhaustive": true
  }
};
