/**
 * GENERATED by `npm run clues` — do not edit.
 *
 * Every clue in here is measured by exhaustive search over the real substrate,
 * so a tier-one hint is a fact rather than an author's opinion. The search is
 * far too slow to run on a phone, which is why it is a table.
 */

export interface LevelClues {
  optimum: { parts: number; depth: number } | null;
  par: { components: number; ticks: number };
  structure: string[];
  netlist: string[];
  exhaustive: boolean;
}

export const CLUES: Record<string, LevelClues> = {
  "continuity": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "No node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = a"
    ],
    "exhaustive": true
  },
  "invert": {
    "optimum": {
      "parts": 1,
      "depth": 1
    },
    "par": {
      "components": 1,
      "ticks": 1
    },
    "structure": [
      "No node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = a",
      "n1 = NOT(n0)"
    ],
    "exhaustive": true
  },
  "fanout": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "No node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = a"
    ],
    "exhaustive": true
  },
  "either": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "One node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = a | b"
    ],
    "exhaustive": true
  },
  "crossing": {
    "optimum": {
      "parts": 0,
      "depth": 0
    },
    "par": {
      "components": 0,
      "ticks": 0
    },
    "structure": [
      "No node is driven by more than one thing."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a"
    ],
    "exhaustive": true
  },
  "neither": {
    "optimum": {
      "parts": 1,
      "depth": 1
    },
    "par": {
      "components": 1,
      "ticks": 1
    },
    "structure": [
      "One node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = a | b",
      "n1 = NOT(n0)"
    ],
    "exhaustive": true
  },
  "not-both": {
    "optimum": {
      "parts": 2,
      "depth": 1
    },
    "par": {
      "components": 2,
      "ticks": 1
    },
    "structure": [
      "One node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = NOT(n0) | NOT(n1)"
    ],
    "exhaustive": true
  },
  "both": {
    "optimum": {
      "parts": 3,
      "depth": 2
    },
    "par": {
      "components": 3,
      "ticks": 2
    },
    "structure": [
      "One node is driven by more than one thing.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = NOT(n0) | NOT(n1)",
      "n3 = NOT(n2)"
    ],
    "exhaustive": true
  },
  "copy": {
    "optimum": {
      "parts": 4,
      "depth": 2
    },
    "par": {
      "components": 4,
      "ticks": 2
    },
    "structure": [
      "No node is driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = c",
      "n1 = b",
      "n2 = OR(n0,n1)",
      "n3 = NOT(n2)",
      "n4 = a",
      "n5 = OR(n1,n4)",
      "n6 = NOT(n5)"
    ],
    "exhaustive": true
  },
  "one-or-other": {
    "optimum": {
      "parts": 6,
      "depth": 2
    },
    "par": {
      "components": 6,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = NOT(n0) | BUF(n1)",
      "n3 = NOT(n1) | BUF(n0)",
      "n4 = NOT(n2) | NOT(n3)"
    ],
    "exhaustive": true
  },
  "half-adder": {
    "optimum": {
      "parts": 7,
      "depth": 3
    },
    "par": {
      "components": 9,
      "ticks": 2
    },
    "structure": [
      "2 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = b",
      "n1 = a",
      "n2 = OR(n0,n1)",
      "n3 = NOT(n0) | NOT(n1)",
      "n4 = NOT(n3)",
      "n5 = NOT(n2) | NOT(n3)",
      "n6 = NOT(n5)"
    ],
    "exhaustive": true
  },
  "full-adder": {
    "optimum": null,
    "par": {
      "components": 18,
      "ticks": 4
    },
    "structure": [
      "9 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = a",
      "n1 = NOT(n6) | NOT(n7)",
      "n2 = NOT(n9) | NOT(n10)",
      "n3 = b",
      "n4 = NOT(n8) | NOT(n11)",
      "n5 = cin",
      "n6 = NOT(n0) | BUF(n3)",
      "n7 = NOT(n3) | BUF(n0)",
      "n8 = NOT(n0) | NOT(n3)",
      "n9 = NOT(n1) | BUF(n5)",
      "n10 = NOT(n5) | BUF(n1)",
      "n11 = NOT(n1) | NOT(n5)"
    ],
    "exhaustive": true
  },
  "hold": {
    "optimum": {
      "parts": 1,
      "depth": 0
    },
    "par": {
      "components": 1,
      "ticks": 0
    },
    "structure": [
      "One node is driven by more than one thing.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: BUF."
    ],
    "netlist": [
      "n0 = a | BUF(n0)"
    ],
    "exhaustive": true
  },
  "set-reset": {
    "optimum": {
      "parts": 2,
      "depth": 1
    },
    "par": {
      "components": 2,
      "ticks": 1
    },
    "structure": [
      "2 of its nodes are driven by more than one thing.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = s | NOT(n1)",
      "n1 = r | NOT(n0)"
    ],
    "exhaustive": true
  },
  "enable": {
    "optimum": {
      "parts": 5,
      "depth": 2
    },
    "par": {
      "components": 5,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = s | NOT(n2)",
      "n1 = en | NOT(n2)",
      "n2 = r | NOT(n0) | NOT(n1)",
      "n3 = NOT(n2)"
    ],
    "exhaustive": true
  },
  "gated": {
    "optimum": null,
    "par": {
      "components": 6,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components.",
      "It places one of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d",
      "n1 = NOT(n0) | NOT(n3)",
      "n2 = NOT(n1) | NOT(n4)",
      "n3 = en",
      "n4 = BUF(n3) | NOT(n2)"
    ],
    "exhaustive": false
  },
  "edge": {
    "optimum": null,
    "par": {
      "components": 13,
      "ticks": 5
    },
    "structure": [
      "6 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d",
      "n1 = NOT(n5) | NOT(n6)",
      "n2 = clk",
      "n3 = NOT(n2)",
      "n4 = NOT(n7) | NOT(n8)",
      "n5 = NOT(n0) | NOT(n3)",
      "n6 = NOT(n1) | BUF(n3)",
      "n7 = NOT(n1) | NOT(n2)",
      "n8 = NOT(n4) | BUF(n2)"
    ],
    "exhaustive": false
  },
  "divide": {
    "optimum": {
      "parts": 8,
      "depth": 5
    },
    "par": {
      "components": 14,
      "ticks": 3
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 2 different components.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = clk",
      "n1 = NOT(n0) | NOT(n2)",
      "n2 = NOT(n0)",
      "n3 = NOT(n1) | NOT(n4)",
      "n4 = NOT(n1) | NOT(n3)",
      "n5 = NOT(n4)"
    ],
    "exhaustive": true
  },
  "two-of-them": {
    "optimum": null,
    "par": {
      "components": 26,
      "ticks": 5
    },
    "structure": [
      "12 of its nodes are driven by more than one thing.",
      "One signal is read by 6 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d0",
      "n1 = NOT(n9) | NOT(n10)",
      "n2 = clk",
      "n3 = d1",
      "n4 = NOT(n15) | NOT(n16)",
      "n5 = NOT(n2)",
      "n6 = NOT(n7) | NOT(n8)",
      "n7 = NOT(n0) | NOT(n5)",
      "n8 = NOT(n6) | BUF(n5)",
      "n9 = NOT(n6) | NOT(n2)",
      "n10 = NOT(n1) | BUF(n2)",
      "n11 = NOT(n2)",
      "n12 = NOT(n13) | NOT(n14)",
      "n13 = NOT(n3) | NOT(n11)",
      "n14 = NOT(n12) | BUF(n11)",
      "n15 = NOT(n12) | NOT(n2)",
      "n16 = NOT(n4) | BUF(n2)"
    ],
    "exhaustive": false
  },
  "only-when-told": {
    "optimum": null,
    "par": {
      "components": 19,
      "ticks": 4
    },
    "structure": [
      "9 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It places one of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d",
      "n1 = NOT(n0) | NOT(n3)",
      "n2 = NOT(n1) | NOT(n6)",
      "n3 = we",
      "n4 = NOT(n11) | NOT(n12)",
      "n5 = clk",
      "n6 = BUF(n3) | NOT(n4)",
      "n7 = NOT(n5)",
      "n8 = NOT(n9) | NOT(n10)",
      "n9 = NOT(n2) | NOT(n7)",
      "n10 = NOT(n8) | BUF(n7)",
      "n11 = NOT(n8) | NOT(n5)",
      "n12 = NOT(n4) | BUF(n5)"
    ],
    "exhaustive": false
  },
  "count-to-three": {
    "optimum": null,
    "par": {
      "components": 28,
      "ticks": 6
    },
    "structure": [
      "12 of its nodes are driven by more than one thing.",
      "One signal is read by 4 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = NOT(n1)",
      "n1 = NOT(n9) | NOT(n10)",
      "n2 = clk",
      "n3 = NOT(n4)",
      "n4 = NOT(n15) | NOT(n16)",
      "n5 = NOT(n2)",
      "n6 = NOT(n7) | NOT(n8)",
      "n7 = NOT(n0) | NOT(n5)",
      "n8 = NOT(n6) | BUF(n5)",
      "n9 = NOT(n6) | NOT(n2)",
      "n10 = NOT(n1) | BUF(n2)",
      "n11 = NOT(n0)",
      "n12 = NOT(n13) | NOT(n14)",
      "n13 = NOT(n3) | NOT(n11)",
      "n14 = NOT(n12) | BUF(n11)",
      "n15 = NOT(n12) | NOT(n0)",
      "n16 = NOT(n4) | BUF(n0)"
    ],
    "exhaustive": true
  },
  "one-of-four": {
    "optimum": null,
    "par": {
      "components": 12,
      "ticks": 2
    },
    "structure": [
      "4 of its nodes are driven by more than one thing.",
      "One signal is read by 4 different components.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = a",
      "n1 = BUF(n0) | BUF(n3)",
      "n2 = NOT(n1)",
      "n3 = b",
      "n4 = NOT(n0) | BUF(n3)",
      "n5 = NOT(n4)",
      "n6 = BUF(n0) | NOT(n3)",
      "n7 = NOT(n6)",
      "n8 = NOT(n0) | NOT(n3)",
      "n9 = NOT(n8)"
    ],
    "exhaustive": true
  },
  "naught-and-one": {
    "optimum": {
      "parts": 3,
      "depth": 3
    },
    "par": {
      "components": 3,
      "ticks": 1
    },
    "structure": [
      "No node is driven by more than one thing.",
      "One signal is read by 2 different components."
    ],
    "netlist": [
      "n0 = x",
      "n1 = NOT(n0)",
      "n2 = OR(n0,n1)",
      "n3 = NOT(n2)"
    ],
    "exhaustive": true
  },
  "every-digit": {
    "optimum": null,
    "par": {
      "components": 8,
      "ticks": 1
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = n0",
      "n1 = n1",
      "n2 = n2",
      "n3 = n3",
      "n4 = NOT(n1)",
      "n5 = NOT(n1) | BUF(n1)",
      "n6 = NOT(n2)",
      "n7 = BUF(n0) | BUF(n2)",
      "n8 = BUF(n2) | BUF(n3)"
    ],
    "exhaustive": false
  },
  "show-the-count": {
    "optimum": null,
    "par": {
      "components": 49,
      "ticks": 8
    },
    "structure": [
      "19 of its nodes are driven by more than one thing.",
      "One signal is read by 6 different components.",
      "It places 3 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = clk",
      "n1 = NOT(n19) | NOT(n20)",
      "n2 = NOT(n27)",
      "n3 = NOT(n4)",
      "n4 = NOT(n28)",
      "n5 = NOT(n4) | BUF(n4)",
      "n6 = NOT(n25) | NOT(n26)",
      "n7 = NOT(n29)",
      "n8 = NOT(n7)",
      "n9 = NOT(n30)",
      "n10 = BUF(n2) | BUF(n7)",
      "n11 = BUF(n2)",
      "n12 = BUF(n7) | BUF(n9)",
      "n13 = NOT(n1)",
      "n14 = NOT(n6)",
      "n15 = NOT(n0)",
      "n16 = NOT(n17) | NOT(n18)",
      "n17 = NOT(n13) | NOT(n15)",
      "n18 = NOT(n16) | BUF(n15)",
      "n19 = NOT(n16) | NOT(n0)",
      "n20 = NOT(n1) | BUF(n0)",
      "n21 = NOT(n13)",
      "n22 = NOT(n23) | NOT(n24)",
      "n23 = NOT(n14) | NOT(n21)",
      "n24 = NOT(n22) | BUF(n21)",
      "n25 = NOT(n22) | NOT(n13)",
      "n26 = NOT(n6) | BUF(n13)",
      "n27 = BUF(n1) | BUF(n6)",
      "n28 = NOT(n1) | BUF(n6)",
      "n29 = BUF(n1) | NOT(n6)",
      "n30 = NOT(n1) | NOT(n6)"
    ],
    "exhaustive": false
  },
  "clear-it": {
    "optimum": {
      "parts": 5,
      "depth": 3
    },
    "par": {
      "components": 8,
      "ticks": 2
    },
    "structure": [
      "3 of its nodes are driven by more than one thing.",
      "One signal is read by 3 different components.",
      "It contains a loop — something reads its own output, eventually.",
      "Every component in it is the same kind: NOT."
    ],
    "netlist": [
      "n0 = d | NOT(n2)",
      "n1 = en | NOT(n2)",
      "n2 = clr | NOT(n0) | NOT(n1)",
      "n3 = NOT(n2)"
    ],
    "exhaustive": false
  },
  "clear-on-the-edge": {
    "optimum": null,
    "par": {
      "components": 17,
      "ticks": 5
    },
    "structure": [
      "6 of its nodes are driven by more than one thing.",
      "One signal is read by 4 different components.",
      "It places 2 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = d",
      "n1 = clk",
      "n2 = NOT(n1)",
      "n3 = NOT(n6) | NOT(n7)",
      "n4 = clr",
      "n5 = NOT(n8) | NOT(n9)",
      "n6 = NOT(n0) | NOT(n2) | BUF(n4)",
      "n7 = BUF(n2) | BUF(n4) | NOT(n3)",
      "n8 = NOT(n3) | NOT(n1) | BUF(n4)",
      "n9 = BUF(n1) | BUF(n4) | NOT(n5)"
    ],
    "exhaustive": false
  },
  "decade": {
    "optimum": null,
    "par": {
      "components": 75,
      "ticks": 12
    },
    "structure": [
      "26 of its nodes are driven by more than one thing.",
      "One signal is read by 16 different components.",
      "It places 4 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = NOT(n5)",
      "n1 = NOT(n6)",
      "n2 = NOT(n7)",
      "n3 = NOT(n8)",
      "n4 = clk",
      "n5 = NOT(n15) | NOT(n16)",
      "n6 = NOT(n21) | NOT(n22)",
      "n7 = NOT(n27) | NOT(n28)",
      "n8 = NOT(n33) | NOT(n34)",
      "n9 = clr | NOT(n10)",
      "n10 = NOT(n8) | NOT(n6)",
      "n11 = NOT(n4)",
      "n12 = NOT(n13) | NOT(n14)",
      "n13 = NOT(n0) | NOT(n11) | BUF(n9)",
      "n14 = BUF(n11) | BUF(n9) | NOT(n12)",
      "n15 = NOT(n12) | NOT(n4) | BUF(n9)",
      "n16 = BUF(n4) | BUF(n9) | NOT(n5)",
      "n17 = NOT(n0)",
      "n18 = NOT(n19) | NOT(n20)",
      "n19 = NOT(n1) | NOT(n17) | BUF(n9)",
      "n20 = BUF(n17) | BUF(n9) | NOT(n18)",
      "n21 = NOT(n18) | NOT(n0) | BUF(n9)",
      "n22 = BUF(n0) | BUF(n9) | NOT(n6)",
      "n23 = NOT(n1)",
      "n24 = NOT(n25) | NOT(n26)",
      "n25 = NOT(n2) | NOT(n23) | BUF(n9)",
      "n26 = BUF(n23) | BUF(n9) | NOT(n24)",
      "n27 = NOT(n24) | NOT(n1) | BUF(n9)",
      "n28 = BUF(n1) | BUF(n9) | NOT(n7)",
      "n29 = NOT(n2)",
      "n30 = NOT(n31) | NOT(n32)",
      "n31 = NOT(n3) | NOT(n29) | BUF(n9)",
      "n32 = BUF(n29) | BUF(n9) | NOT(n30)",
      "n33 = NOT(n30) | NOT(n2) | BUF(n9)",
      "n34 = BUF(n2) | BUF(n9) | NOT(n8)"
    ],
    "exhaustive": false
  },
  "pass-it-on": {
    "optimum": null,
    "par": {
      "components": 68,
      "ticks": 3
    },
    "structure": [
      "24 of its nodes are driven by more than one thing.",
      "One signal is read by 16 different components.",
      "It places 4 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = NOT(n11) | NOT(n12)",
      "n1 = NOT(n17) | NOT(n18)",
      "n2 = NOT(n23) | NOT(n24)",
      "n3 = d",
      "n4 = clk",
      "n5 = NOT(n29) | NOT(n30)",
      "n6 = clr",
      "n7 = NOT(n4)",
      "n8 = NOT(n9) | NOT(n10)",
      "n9 = NOT(n3) | NOT(n7) | BUF(n6)",
      "n10 = BUF(n7) | BUF(n6) | NOT(n8)",
      "n11 = NOT(n8) | NOT(n4) | BUF(n6)",
      "n12 = BUF(n4) | BUF(n6) | NOT(n0)",
      "n13 = NOT(n4)",
      "n14 = NOT(n15) | NOT(n16)",
      "n15 = NOT(n0) | NOT(n13) | BUF(n6)",
      "n16 = BUF(n13) | BUF(n6) | NOT(n14)",
      "n17 = NOT(n14) | NOT(n4) | BUF(n6)",
      "n18 = BUF(n4) | BUF(n6) | NOT(n1)",
      "n19 = NOT(n4)",
      "n20 = NOT(n21) | NOT(n22)",
      "n21 = NOT(n1) | NOT(n19) | BUF(n6)",
      "n22 = BUF(n19) | BUF(n6) | NOT(n20)",
      "n23 = NOT(n20) | NOT(n4) | BUF(n6)",
      "n24 = BUF(n4) | BUF(n6) | NOT(n2)",
      "n25 = NOT(n4)",
      "n26 = NOT(n27) | NOT(n28)",
      "n27 = NOT(n2) | NOT(n25) | BUF(n6)",
      "n28 = BUF(n25) | BUF(n6) | NOT(n26)",
      "n29 = NOT(n26) | NOT(n4) | BUF(n6)",
      "n30 = BUF(n4) | BUF(n6) | NOT(n5)"
    ],
    "exhaustive": false
  },
  "round-and-round": {
    "optimum": null,
    "par": {
      "components": 68,
      "ticks": 3
    },
    "structure": [
      "24 of its nodes are driven by more than one thing.",
      "One signal is read by 16 different components.",
      "It places one of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = clk",
      "n1 = clr",
      "n2 = st | NOT(n28) | NOT(n29)",
      "n3 = NOT(n10) | NOT(n11)",
      "n4 = NOT(n16) | NOT(n17)",
      "n5 = NOT(n22) | NOT(n23)",
      "n6 = NOT(n0)",
      "n7 = NOT(n8) | NOT(n9)",
      "n8 = NOT(n2) | NOT(n6) | BUF(n1)",
      "n9 = BUF(n6) | BUF(n1) | NOT(n7)",
      "n10 = NOT(n7) | NOT(n0) | BUF(n1)",
      "n11 = BUF(n0) | BUF(n1) | NOT(n3)",
      "n12 = NOT(n0)",
      "n13 = NOT(n14) | NOT(n15)",
      "n14 = NOT(n3) | NOT(n12) | BUF(n1)",
      "n15 = BUF(n12) | BUF(n1) | NOT(n13)",
      "n16 = NOT(n13) | NOT(n0) | BUF(n1)",
      "n17 = BUF(n0) | BUF(n1) | NOT(n4)",
      "n18 = NOT(n0)",
      "n19 = NOT(n20) | NOT(n21)",
      "n20 = NOT(n4) | NOT(n18) | BUF(n1)",
      "n21 = BUF(n18) | BUF(n1) | NOT(n19)",
      "n22 = NOT(n19) | NOT(n0) | BUF(n1)",
      "n23 = BUF(n0) | BUF(n1) | NOT(n5)",
      "n24 = NOT(n0)",
      "n25 = NOT(n26) | NOT(n27)",
      "n26 = NOT(n5) | NOT(n24) | BUF(n1)",
      "n27 = BUF(n24) | BUF(n1) | NOT(n25)",
      "n28 = NOT(n25) | NOT(n0) | BUF(n1)",
      "n29 = BUF(n0) | BUF(n1) | NOT(n2)"
    ],
    "exhaustive": false
  },
  "ten-in-a-ring": {
    "optimum": null,
    "par": {
      "components": 170,
      "ticks": 3
    },
    "structure": [
      "60 of its nodes are driven by more than one thing.",
      "One signal is read by 40 different components.",
      "It places 4 of the blocks you have already earned.",
      "This is a working answer, not necessarily the smallest one."
    ],
    "netlist": [
      "n0 = st | NOT(n70) | NOT(n71)",
      "n1 = NOT(n16) | NOT(n17)",
      "n2 = NOT(n22) | NOT(n23)",
      "n3 = clr",
      "n4 = NOT(n28) | NOT(n29)",
      "n5 = NOT(n34) | NOT(n35)",
      "n6 = clk",
      "n7 = NOT(n40) | NOT(n41)",
      "n8 = NOT(n46) | NOT(n47)",
      "n9 = NOT(n52) | NOT(n53)",
      "n10 = NOT(n58) | NOT(n59)",
      "n11 = NOT(n64) | NOT(n65)",
      "n12 = NOT(n6)",
      "n13 = NOT(n14) | NOT(n15)",
      "n14 = NOT(n0) | NOT(n12) | BUF(n3)",
      "n15 = BUF(n12) | BUF(n3) | NOT(n13)",
      "n16 = NOT(n13) | NOT(n6) | BUF(n3)",
      "n17 = BUF(n6) | BUF(n3) | NOT(n1)",
      "n18 = NOT(n6)",
      "n19 = NOT(n20) | NOT(n21)",
      "n20 = NOT(n1) | NOT(n18) | BUF(n3)",
      "n21 = BUF(n18) | BUF(n3) | NOT(n19)",
      "n22 = NOT(n19) | NOT(n6) | BUF(n3)",
      "n23 = BUF(n6) | BUF(n3) | NOT(n2)",
      "n24 = NOT(n6)",
      "n25 = NOT(n26) | NOT(n27)",
      "n26 = NOT(n2) | NOT(n24) | BUF(n3)",
      "n27 = BUF(n24) | BUF(n3) | NOT(n25)",
      "n28 = NOT(n25) | NOT(n6) | BUF(n3)",
      "n29 = BUF(n6) | BUF(n3) | NOT(n4)",
      "n30 = NOT(n6)",
      "n31 = NOT(n32) | NOT(n33)",
      "n32 = NOT(n4) | NOT(n30) | BUF(n3)",
      "n33 = BUF(n30) | BUF(n3) | NOT(n31)",
      "n34 = NOT(n31) | NOT(n6) | BUF(n3)",
      "n35 = BUF(n6) | BUF(n3) | NOT(n5)",
      "n36 = NOT(n6)",
      "n37 = NOT(n38) | NOT(n39)",
      "n38 = NOT(n5) | NOT(n36) | BUF(n3)",
      "n39 = BUF(n36) | BUF(n3) | NOT(n37)",
      "n40 = NOT(n37) | NOT(n6) | BUF(n3)",
      "n41 = BUF(n6) | BUF(n3) | NOT(n7)",
      "n42 = NOT(n6)",
      "n43 = NOT(n44) | NOT(n45)",
      "n44 = NOT(n7) | NOT(n42) | BUF(n3)",
      "n45 = BUF(n42) | BUF(n3) | NOT(n43)",
      "n46 = NOT(n43) | NOT(n6) | BUF(n3)",
      "n47 = BUF(n6) | BUF(n3) | NOT(n8)",
      "n48 = NOT(n6)",
      "n49 = NOT(n50) | NOT(n51)",
      "n50 = NOT(n8) | NOT(n48) | BUF(n3)",
      "n51 = BUF(n48) | BUF(n3) | NOT(n49)",
      "n52 = NOT(n49) | NOT(n6) | BUF(n3)",
      "n53 = BUF(n6) | BUF(n3) | NOT(n9)",
      "n54 = NOT(n6)",
      "n55 = NOT(n56) | NOT(n57)",
      "n56 = NOT(n9) | NOT(n54) | BUF(n3)",
      "n57 = BUF(n54) | BUF(n3) | NOT(n55)",
      "n58 = NOT(n55) | NOT(n6) | BUF(n3)",
      "n59 = BUF(n6) | BUF(n3) | NOT(n10)",
      "n60 = NOT(n6)",
      "n61 = NOT(n62) | NOT(n63)",
      "n62 = NOT(n10) | NOT(n60) | BUF(n3)",
      "n63 = BUF(n60) | BUF(n3) | NOT(n61)",
      "n64 = NOT(n61) | NOT(n6) | BUF(n3)",
      "n65 = BUF(n6) | BUF(n3) | NOT(n11)",
      "n66 = NOT(n6)",
      "n67 = NOT(n68) | NOT(n69)",
      "n68 = NOT(n11) | NOT(n66) | BUF(n3)",
      "n69 = BUF(n66) | BUF(n3) | NOT(n67)",
      "n70 = NOT(n67) | NOT(n6) | BUF(n3)",
      "n71 = BUF(n6) | BUF(n3) | NOT(n0)"
    ],
    "exhaustive": false
  }
};
