/**
 * Turns the balance analysis into a document you can read and diff.
 *
 * Regenerate with `npm run balance`. Committing the output means a design
 * change that shifts the curve shows up as a diff in review, not as a surprise
 * three levels later.
 */

import { Level } from '../game/level';
import { LevelAnalysis, PERSONAS, analyseAll, budgetFor } from './personas';
import { describe as showCircuit } from './synth';

const n = (v: number | null | undefined) => (v === null || v === undefined ? '—' : String(v));

function personaCell(a: LevelAnalysis, id: string): string {
  const r = a.results.find((x) => x.persona === id);
  if (!r) return '—';
  if (!r.solved) return r.exhaustive ? `none ≤${budgetFor(a.targets.k).maxParts}` : 'truncated';
  return `${r.best!.parts}p / ${r.best!.depth}t`;
}

export function buildReport(levels: Level[]): string {
  const rows = analyseAll(levels);
  const searched = rows.filter((a) => a.targets.targets !== null);
  const out: string[] = [];

  out.push('# Balance');
  out.push('');
  out.push(
    'Generated by `npm run balance`. Every number here is measured by exhaustive',
    'search over the real substrate — nets, free merges, destructive fan-in — not',
    'by Boolean algebra and not by hand.',
    '',
    '**A persona is a policy, not a person.** Each one is a restricted vocabulary',
    'searched to exhaustion, so what it measures is a property of the level. When',
    'Wire-only needs eight components for XOR and the full vocabulary needs six,',
    'that is a fact about XOR in this substrate.',
    '',
  );

  out.push('## Personas', '');
  out.push('| persona | vocabulary | what a result means |', '|---|---|---|');
  for (const p of PERSONAS) {
    out.push(`| **${p.name}** | ${p.kinds.map((k) => k.toUpperCase()).join(', ')} + merging | ${p.reads} |`);
  }
  out.push('');

  out.push('## The curve', '');
  out.push(
    '| # | level | par | optimum | wire-only | tool saves | headroom | frontier |',
    '|---|---|---|---|---|---|---|---|',
  );
  rows.forEach((a, i) => {
    if (!a.targets.targets) {
      out.push(`| ${i + 1} | ${a.title} | ${a.par.components}c / ${a.par.ticks}t | *${a.targets.why}* | — | — | — | — |`);
      return;
    }
    out.push(
      `| ${i + 1} | ${a.title} | ${a.par.components}c / ${a.par.ticks}t | ${personaCell(a, 'optimiser')} ` +
        `| ${personaCell(a, 'wire-only')} | ${n(a.toolSaving)} | ${n(a.headroom)} | ${a.frontierSize} |`,
    );
  });
  out.push('');
  out.push(
    '**par** is what the level\'s reference solution scores — the number shown to the',
    'player. **optimum** is the cheapest circuit that exists. **headroom** is the gap',
    'between them, which is room for the player to beat par rather than a mistake.',
    '**tool saves** is what the level\'s newer components buy over inverters alone;',
    'a zero there means the level does not reward what it teaches.',
    '',
  );

  const flat = searched.filter((a) => !a.beyondBudget && a.frontierSize <= 1);
  const tense = searched.filter((a) => a.frontierSize > 1);

  out.push('## Where the three metrics actually bite', '');
  out.push(
    'A level with a single non-dominated solution has no trade-off: components,',
    'ticks and area cannot be played against each other, so its score is a target',
    'rather than a choice. That is fine for a teaching level and hollow for a late',
    'one.',
    '',
  );
  if (tense.length) {
    out.push('**Real trade-offs:**', '');
    for (const a of tense) {
      const f = a.results.find((r) => r.persona === 'optimiser')!.frontier;
      out.push(`- **${a.title}** — ${f.map((s) => `${s.parts}p/${s.depth}t`).join('  ↔  ')}`);
    }
    out.push('');
  }
  out.push(`**One dominant answer:** ${flat.map((a) => a.title).join(', ') || 'none'}`, '');

  out.push('## BUF against OR', '');
  out.push(
    'Both buy the same thing — one extra use of a signal — and both cost one',
    'component and one tick. BUF pays on the **signal** side, manufacturing a',
    'second independent copy so a destructive merge stays affordable. OR pays on',
    'the **join** side, manufacturing a join that reads instead of consuming.',
    '',
    'They tie wherever a signal is simply used twice. They come apart wherever an',
    'intermediate result is shared between outputs, because OR lets one value',
    'serve two consumers while BUF has to make another of it.',
    '',
    '| level | Copier (BUF) | Gater (OR) | winner |',
    '|---|---|---|---|',
  );
  for (const a of searched) {
    const c = a.results.find((r) => r.persona === 'copier');
    const gg = a.results.find((r) => r.persona === 'gater');
    if (!c?.solved || !gg?.solved) continue;
    const winner =
      c.best!.parts === gg.best!.parts
        ? c.best!.depth === gg.best!.depth
          ? 'tie'
          : c.best!.depth < gg.best!.depth
            ? '**BUF** (shallower)'
            : '**OR** (shallower)'
        : c.best!.parts < gg.best!.parts
          ? '**BUF**'
          : '**OR**';
    out.push(
      `| ${a.title} | ${c.best!.parts}p / ${c.best!.depth}t | ${gg.best!.parts}p / ${gg.best!.depth}t | ${winner} |`,
    );
  }
  out.push('');

  out.push('## Witnesses', '');
  out.push('The cheapest circuit the search found, as a netlist. `nX` are nets; drivers', 'sharing a net are a free merge.', '');
  for (const a of searched) {
    if (!a.witness) continue;
    const outs = a.witness.circuit.outputs
      .map((netIdx, i) => `${a.targets.outputs[i]}=n${netIdx}`)
      .join(', ');
    out.push(
      `- **${a.title}** (${a.witness.parts}p / ${a.witness.depth}t) — ` +
        `\`${showCircuit(a.witness.circuit, a.targets.inputs)}\`  →  *${outs}*`,
    );
  }
  out.push('');

  out.push('## What the model cannot see', '');
  out.push(
    '- **Area.** The third metric needs placement and routing; the search works on',
    '  netlists, so area is only ever measured from the reference solution.',
    '- **Anything with state.** The search is combinational. Sequential levels need',
    '  a different model.',
    '- **Levels above three inputs.** The full adder is past the enumeration budget.',
    '  A "none" result there means *no circuit at or below the part cap*, never',
    '  "unsolvable".',
    '- **Whether any of it is fun.** This measures the shape of the solution space.',
    '  It says nothing about whether finding a solution feels good.',
    '',
  );

  return out.join('\n');
}
